name: Build

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: fedora-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: bash ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fedora-Remix-Mobility-SDM845-OnePlus
          path: ./fedora-kiwi-descriptions/outdir-build/out/*
